<div class="flex flex-col items-center">
    <div id="memory-board" class="grid grid-cols-4 gap-2 mb-4">
        <!-- Generated by JS -->
    </div>
    <p id="memory-status" class="text-xl font-bold mb-4">Find all pairs!</p>
    <button onclick="initMemoryGame()" class="bg-gray-600 px-4 py-2 rounded">Reset</button>
</div>

<style>
    .memory-card {
        width: 80px;
        height: 80px;
        background-color: #2a475e;
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 2rem;
        cursor: pointer;
        border-radius: 0.5rem;
        transition: transform 0.3s;
    }
    .memory-card.flipped {
        background-color: #66c0f4;
        transform: rotateY(180deg);
    }
</style>

<script>
    const emojis = ['🍎', '🍌', '🍇', '🍉', '🍒', '🍓', '🥑', '🍍'];
    let cards = [...emojis, ...emojis];
    let flippedCards = [];
    let matchedPairs = 0;
    let lockBoard = false;

    function shuffle(array) {
        for (let i = array.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [array[i], array[j]] = [array[j], array[i]];
        }
    }

    function initMemoryGame() {
        const board = document.getElementById('memory-board');
        board.innerHTML = '';
        shuffle(cards);
        flippedCards = [];
        matchedPairs = 0;
        lockBoard = false;
        document.getElementById('memory-status').innerText = "Find all pairs!";

        cards.forEach((emoji, index) => {
            const card = document.createElement('div');
            card.classList.add('memory-card');
            card.dataset.emoji = emoji;
            card.dataset.index = index;
            card.innerText = ''; // Hidden initially
            card.onclick = () => flipCard(card);
            board.appendChild(card);
        });
    }

    function flipCard(card) {
        if (lockBoard || card.classList.contains('flipped') || flippedCards.includes(card)) return;

        card.classList.add('flipped');
        card.innerText = card.dataset.emoji;
        flippedCards.push(card);

        if (flippedCards.length === 2) {
            checkMatch();
        }
    }

    function checkMatch() {
        lockBoard = true;
        const [card1, card2] = flippedCards;

        if (card1.dataset.emoji === card2.dataset.emoji) {
            matchedPairs++;
            flippedCards = [];
            lockBoard = false;
            if (matchedPairs === emojis.length) {
                document.getElementById('memory-status').innerText = "You Win!";
                setTimeout(() => claimReward('memory'), 1000);
            }
        } else {
            setTimeout(() => {
                card1.classList.remove('flipped');
                card1.innerText = '';
                card2.classList.remove('flipped');
                card2.innerText = '';
                flippedCards = [];
                lockBoard = false;
            }, 1000);
        }
    }

    initMemoryGame();
</script>
