<div class="max-w-2xl mx-auto bg-[#16202d] p-6 rounded-lg shadow-lg border border-gray-700">
    <h3 class="text-2xl font-bold text-center mb-6 text-[#66c0f4]">🐍 Snake & Ladders 🪜</h3>

    <div class="flex flex-col md:flex-row gap-8 items-start">
        
        {{-- BOARD --}}
        <div class="relative">
            <div id="sl-board" class="grid grid-cols-10 gap-1 bg-[#2a3f5a] p-2 rounded border border-gray-600 w-[350px] h-[350px] sm:w-[400px] sm:h-[400px]">
                {{-- Grid generated by JS --}}
            </div>
            
            {{-- Players --}}
            <div id="p1-token" class="absolute w-6 h-6 bg-blue-500 rounded-full border-2 border-white shadow-lg transition-all duration-500 z-10 flex items-center justify-center text-[10px] font-bold" style="bottom: 10px; left: 10px;">P1</div>
            <div id="cpu-token" class="absolute w-6 h-6 bg-red-500 rounded-full border-2 border-white shadow-lg transition-all duration-500 z-10 flex items-center justify-center text-[10px] font-bold" style="bottom: 10px; left: 10px;">CPU</div>
        </div>

        {{-- CONTROLS --}}
        <div class="flex-1 w-full">
            <div class="bg-[#1b2838] p-4 rounded border border-gray-600 mb-4">
                <div class="flex justify-between items-center mb-2">
                    <span class="text-blue-400 font-bold">Player (You)</span>
                    <span id="p1-pos" class="text-white font-mono">Pos: 1</span>
                </div>
                <div class="flex justify-between items-center">
                    <span class="text-red-400 font-bold">CPU</span>
                    <span id="cpu-pos" class="text-white font-mono">Pos: 1</span>
                </div>
            </div>

            <div id="game-status" class="text-center text-yellow-500 font-bold mb-4 h-6">Your Turn!</div>

            <div class="flex justify-center mb-6">
                <div id="dice-display" class="w-16 h-16 bg-white text-black text-4xl font-black flex items-center justify-center rounded shadow-lg border-4 border-gray-300">
                    🎲
                </div>
            </div>

            <button id="roll-btn" onclick="rollDice()" class="w-full bg-green-600 hover:bg-green-500 text-white font-bold py-3 px-4 rounded shadow-lg transition transform hover:scale-105">
                ROLL DICE
            </button>
        </div>
    </div>
</div>

<script>
    const boardSize = 100;
    const snakes = { 16: 6, 47: 26, 49: 11, 56: 53, 62: 19, 64: 60, 87: 24, 93: 73, 95: 75, 98: 78 };
    const ladders = { 1: 38, 4: 14, 9: 31, 21: 42, 28: 84, 36: 44, 51: 67, 71: 91, 80: 100 };
    
    let p1Pos = 1;
    let cpuPos = 1;
    let isPlayerTurn = true;
    let gameOver = false;

    function initBoard() {
        const board = document.getElementById('sl-board');
        board.innerHTML = '';
        
        // Create 100 cells
        for (let i = 100; i >= 1; i--) {
            const cell = document.createElement('div');
            cell.className = 'flex items-center justify-center text-[10px] text-gray-500 font-mono relative';
            cell.innerText = i;
            
            // Color special tiles
            if (snakes[i]) cell.classList.add('bg-red-900/30', 'text-red-400');
            if (ladders[i]) cell.classList.add('bg-green-900/30', 'text-green-400');
            
            // Add Snake/Ladder indicators
            if (snakes[i]) {
                const ind = document.createElement('span');
                ind.innerText = '🐍';
                ind.className = 'absolute text-xs opacity-50';
                cell.appendChild(ind);
            }
            if (ladders[i]) {
                const ind = document.createElement('span');
                ind.innerText = '🪜';
                ind.className = 'absolute text-xs opacity-50';
                cell.appendChild(ind);
            }

            board.appendChild(cell);
        }
        updateTokens();
    }

    function getCoordinates(pos) {
        // Calculate row and col for 10x10 grid (snake pattern)
        // Grid is 100 at top-left (if standard), but let's map to visual grid
        // Visual grid: 
        // Row 0: 100 99 ... 91
        // Row 1: 81 82 ... 90
        // ...
        // Row 9: 1 2 ... 10
        
        // 1-based pos
        let rowFromBottom = Math.floor((pos - 1) / 10); // 0 to 9
        let col = (pos - 1) % 10; // 0 to 9
        
        let visualRow = 9 - rowFromBottom; // 9 is bottom, 0 is top
        let visualCol = rowFromBottom % 2 === 0 ? col : 9 - col; // Zig-zag

        // Calculate pixel offset
        // Assuming grid gap 4px (1rem/4), cell size approx
        // Better to use percentage or fixed step
        // Let's use simple percentage based on container size
        
        return { x: visualCol * 10, y: visualRow * 10 };
    }

    function updateTokens() {
        const p1Coord = getCoordinates(p1Pos);
        const cpuCoord = getCoordinates(cpuPos);
        
        const p1El = document.getElementById('p1-token');
        const cpuEl = document.getElementById('cpu-token');
        
        // Adjust for padding/centering (approximate)
        p1El.style.left = `calc(${p1Coord.x}% + 2%)`;
        p1El.style.top = `calc(${p1Coord.y}% + 2%)`;
        
        cpuEl.style.left = `calc(${cpuCoord.x}% + 2%)`;
        cpuEl.style.top = `calc(${cpuCoord.y}% + 2%)`; // Offset slightly so they don't perfectly overlap?
        
        // If same pos, offset CPU slightly
        if (p1Pos === cpuPos) {
            cpuEl.style.left = `calc(${cpuCoord.x}% + 4%)`;
            cpuEl.style.top = `calc(${cpuCoord.y}% + 4%)`;
        }

        document.getElementById('p1-pos').innerText = `Pos: ${p1Pos}`;
        document.getElementById('cpu-pos').innerText = `Pos: ${cpuPos}`;
    }

    function rollDice() {
        if (!isPlayerTurn || gameOver) return;
        
        const btn = document.getElementById('roll-btn');
        btn.disabled = true;
        btn.classList.add('opacity-50');
        
        const diceVal = Math.floor(Math.random() * 6) + 1;
        animateDice(diceVal, () => {
            movePlayer(diceVal);
        });
    }

    function animateDice(finalVal, callback) {
        const diceEl = document.getElementById('dice-display');
        let count = 0;
        const interval = setInterval(() => {
            diceEl.innerText = ['⚀','⚁','⚂','⚃','⚄','⚅'][Math.floor(Math.random()*6)];
            count++;
            if (count > 10) {
                clearInterval(interval);
                diceEl.innerText = ['⚀','⚁','⚂','⚃','⚄','⚅'][finalVal - 1];
                callback();
            }
        }, 50);
    }

    function movePlayer(steps) {
        let newPos = p1Pos + steps;
        if (newPos > 100) newPos = 100 - (newPos - 100); // Bounce back rule or just stay? Let's stay.
        if (newPos > 100) newPos = p1Pos; // Stay if overshoot
        
        p1Pos = newPos;
        updateTokens();
        
        checkSpecialTiles(p1Pos, (finalPos) => {
            p1Pos = finalPos;
            updateTokens();
            
            if (p1Pos === 100) {
                gameOver = true;
                document.getElementById('game-status').innerText = "YOU WIN!";
                document.getElementById('game-status').className = "text-center text-green-500 font-black text-xl mb-4";
                setTimeout(() => claimReward('snake_ladders'), 1000);
            } else {
                isPlayerTurn = false;
                document.getElementById('game-status').innerText = "CPU Turn...";
                setTimeout(cpuTurn, 1000);
            }
        });
    }

    function cpuTurn() {
        if (gameOver) return;
        
        const diceVal = Math.floor(Math.random() * 6) + 1;
        animateDice(diceVal, () => {
            let newPos = cpuPos + diceVal;
            if (newPos > 100) newPos = cpuPos;
            
            cpuPos = newPos;
            updateTokens();
            
            checkSpecialTiles(cpuPos, (finalPos) => {
                cpuPos = finalPos;
                updateTokens();
                
                if (cpuPos === 100) {
                    gameOver = true;
                    document.getElementById('game-status').innerText = "CPU WINS!";
                    document.getElementById('game-status').className = "text-center text-red-500 font-black text-xl mb-4";
                    alert("CPU Won! Try again tomorrow.");
                } else {
                    isPlayerTurn = true;
                    document.getElementById('game-status').innerText = "Your Turn!";
                    const btn = document.getElementById('roll-btn');
                    btn.disabled = false;
                    btn.classList.remove('opacity-50');
                }
            });
        });
    }

    function checkSpecialTiles(pos, callback) {
        setTimeout(() => {
            if (snakes[pos]) {
                document.getElementById('game-status').innerText = "Oh no! Snake! 🐍";
                setTimeout(() => callback(snakes[pos]), 500);
            } else if (ladders[pos]) {
                document.getElementById('game-status').innerText = "Ladder! Up we go! 🪜";
                setTimeout(() => callback(ladders[pos]), 500);
            } else {
                callback(pos);
            }
        }, 500);
    }

    // Init
    initBoard();
</script>
